# Generated by Django 4.1 on 2023-05-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idGenero", models.IntegerField()),
                ("descripcion", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idIngrediente", models.IntegerField()),
                ("descripcion", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("rut", models.IntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("direccion", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="plato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idPlato", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="prueba",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idReserva", models.IntegerField()),
                ("fecha", models.DateField()),
                ("hora", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idRol", models.IntegerField()),
                ("descripcion", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombreUsuario", models.CharField(max_length=50)),
                ("contrasenia", models.CharField(max_length=20)),
            ],
        ),
    ]
